name: UnlimitedSteak
main: usteak\steak
api: 3.0.0
author: secretsilver313
version: 1.0.0
description: "Unlimited Steak"
commands:
  unlimsteak:
     default: op
     permission: unlimsteak.use
     description: gives you the Unlimited steak
